springdoc:
  api-docs:
    path: /api-docs
spring:
  jpa:
    generate-ddl: 'true'
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: 'true'
    hibernate:
      ddl-auto: create-drop
  datasource:
    username: sa
    url: jdbc:h2:file:C:/data/demodb
    driverClassName: org.h2.Driver
    password: password
  h2:
    console:
      enabled: 'true'
server:
  servlet:
    context-path: /sornambigai-backend
  port: '8080'
